import csv

def p(name):
    return "${" + name + "}"

# ==============================================================================
# 1. ROOT LAB TEST CASES (owprov_rbac_v1_root_lab_test_cases.csv)
# ==============================================================================
root_rows = [
    ["TestCaseID","Category","Scenario","Method","Endpoint","RequestBody","ExpectedStatus","Description"],
    
    # --- BOOTSTRAP SYSTEM & OPERATORS ---
    ["ROOT-BOOTSTRAP-0001","Bootstrap","Verify Root Entity exists","GET","/api/v1/entity/0000-0000-0000","","200","ROOT retrieves the system Root Entity to confirm bootstrap status."],
    ["ROOT-BOOTSTRAP-0002","Bootstrap","Create Level 1 Operator A","POST","/api/v1/operator/0000-0000-0000",'{"name":"op-l1-a","registrationId":"operator-a"}',"200","ROOT creates level 1 Operator A which atomically creates its Operator Entity."],
    ["ROOT-BOOTSTRAP-0003","Bootstrap","Create Level 1 Operator B","POST","/api/v1/operator/0000-0000-0000",'{"name":"op-l1-b","registrationId":"operator-b"}',"200","ROOT creates level 1 Operator B which atomically creates its Operator Entity."],
    ["ROOT-BOOTSTRAP-0004","Bootstrap","Create Level 1 Normal Entity 1","POST","/api/v1/entity/0",'{"name":"entity-l1-1","parent":"0000-0000-0000"}',"200","ROOT creates a Normal Entity directly under the Root Entity."],
    ["ROOT-BOOTSTRAP-0005","Bootstrap","Create Level 2 Normal Entity 2","POST","/api/v1/entity/0",'{"name":"entity-l2-1","parent":"' + p("entity_l1_a_id") + '"}',"200","ROOT creates a Normal Entity directly under Operator A Entity."],
    ["ROOT-BOOTSTRAP-0006","Bootstrap","Create Top-level Venue 1","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-l1-1","entity":"' + p("entity_l1_a_id") + '"}',"200","ROOT creates a Venue under Operator A Entity."],
    ["ROOT-BOOTSTRAP-0007","Bootstrap","Create nested Child Venue 2","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-l2-1","parent":"' + p("venue_l1_1_id") + '"}',"200","ROOT creates a nested child Venue under Venue 1."],
    ["ROOT-BOOTSTRAP-0008","Bootstrap","Create Inventory Tag A","POST","/api/v1/inventory/dc6279652f20",'{"serialNumber":"dc6279652f20","name":"tag-a","deviceType":"asus_rt-ax53u","venue":"' + p("venue_l1_1_id") + '","devGroup":"ap","devClass":"venue"}',"200","ROOT creates an inventory device under Venue 1."],
    ["ROOT-BOOTSTRAP-0009","Bootstrap","Create Configuration A","POST","/api/v1/configuration/0000-0000-0000",'{"name":"config-a","deviceTypes":["asus_rt-ax53u"],"entity":"' + p("entity_l1_a_id") + '"}',"200","ROOT creates configuration profile under Operator A Entity."],
    
    # --- BOOTSTRAP CUSTOM POLICIES & ROLES ---
    ["ROOT-BOOTSTRAP-0010","Bootstrap","Create Policy A","POST","/api/v1/managementPolicy/0000-0000-0000",'{"name":"policy-a","entity":"' + p("entity_l1_a_id") + '","entries":[{"resources":["inventory","venue","managementRole"],"access":["FULL"],"effect":"allow"}]}','200','ROOT creates policy profile A under Operator A Entity.'],
    ["ROOT-BOOTSTRAP-0011","Bootstrap","Create Policy B","POST","/api/v1/managementPolicy/0000-0000-0000",'{"name":"policy-b","entity":"' + p("entity_l1_b_id") + '","entries":[{"resources":["venue"],"access":["FULL"],"effect":"allow"}]}','200','ROOT creates policy profile B under Operator B Entity.'],
    ["ROOT-BOOTSTRAP-0012","Bootstrap","Create Policy C","POST","/api/v1/managementPolicy/0000-0000-0000",'{"name":"policy-c","entity":"' + p("entity_l1_a_id") + '","entries":[{"resources":["venue"],"access":["READ"],"effect":"allow"}]}','200','ROOT creates narrow Policy C (Venue read-only) under Operator A Entity.'],
    ["ROOT-BOOTSTRAP-0013","Bootstrap","Create Role A","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-a","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_a_id") + '","users":["11111111-0000-0000-6666-999999999999"]}','200','ROOT binds root user to Policy A under Operator A Entity.'],
    ["ROOT-BOOTSTRAP-0014","Bootstrap","Create Subscriber A","POST","/api/v1/signup?email=suba@doe.com&signupUUID=11223344-5566-7788-9900-aabbccddeeff&owner=" + p("operator_a_id") + "&operatorName=OperatorA","","200","ROOT creates subscriber under Operator A via signup endpoint."],
    
    # --- BOOTSTRAP CUSTOM USERS ---
    ["ROOT-BOOTSTRAP-0015","Bootstrap","Create User Admin A","POST","/api/v1/user",'{"email":"admina@rbac.local","name":"admin-a","currentPassword":"Password123!","userRole":"admin"}','200','ROOT creates administrative user Admin A.'],
    ["ROOT-BOOTSTRAP-0016","Bootstrap","Create User Admin B","POST","/api/v1/user",'{"email":"adminb@rbac.local","name":"admin-b","currentPassword":"Password123!","userRole":"admin"}','200','ROOT creates administrative user Admin B.'],
    ["ROOT-BOOTSTRAP-0017","Bootstrap","Create Role Admin A on Entity A","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-admin-a","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_a_id") + '","users":["' + p("user_admin_a_id") + '"]}','200','ROOT assigns Role Admin A scoping Admin A to Entity A.'],
    ["ROOT-BOOTSTRAP-0018","Bootstrap","Create Role Admin B on Entity B","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-admin-b","entity":"' + p("entity_l1_b_id") + '","managementPolicy":"' + p("policy_b_id") + '","users":["' + p("user_admin_b_id") + '"]}','200','ROOT assigns Role Admin B scoping Admin B to Entity B.'],
    ["ROOT-BOOTSTRAP-0019","Bootstrap","Create Venue Role for Admin A on Venue 1","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-venue-a","entity":"' + p("entity_l1_a_id") + '","venue":"' + p("venue_l1_1_id") + '","managementPolicy":"' + p("policy_c_id") + '","users":["' + p("user_admin_a_id") + '"]}','200','ROOT assigns narrow Venue Role to Admin A on Venue 1.'],
    ["ROOT-BOOTSTRAP-0020","Bootstrap","Login Admin A","POST","/api/v1/oauth2",'{"userId":"admina@rbac.local","password":"Password123!"}','200','Log in to retrieve token for Admin A.'],
    ["ROOT-BOOTSTRAP-0021","Bootstrap","Login Admin B","POST","/api/v1/oauth2",'{"userId":"adminb@rbac.local","password":"Password123!"}','200','Log in to retrieve token for Admin B.'],
    ["ROOT-BOOTSTRAP-0022","Bootstrap","Create User Client A","POST","/api/v1/user",'{"email":"clienta@rbac.local","name":"client-a","currentPassword":"Password123!","userRole":"admin"}','200','ROOT creates user Client A.'],
    ["ROOT-BOOTSTRAP-0023","Bootstrap","Create Role for Client A","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-client-a","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_a_id") + '","users":["' + p("user_client_a_id") + '"]}','200','ROOT assigns management role for Client A.'],
    ["ROOT-BOOTSTRAP-0024","Bootstrap","Admin A creates user delegated-a","POST","/api/v1/user",'{"email":"delegateda@rbac.local","name":"delegated-a","currentPassword":"Password123!","userRole":"admin"}','200','Admin A creates User Delegated A.'],

    # --- BOOTSTRAP DEFAULT 4 POLICIES USERS (ADMIN, NOC, CSR, INSTALLER) ---
    ["ROOT-BOOTSTRAP-0025","Bootstrap","Create User Default Admin","POST","/api/v1/user?entity=" + p("entity_l1_a_id"),'{"email":"defadmin@rbac.local","name":"def-admin","currentPassword":"Password123!","userRole":"admin","owner":"' + p("entity_l1_a_id") + '"}','200','ROOT creates User Default Admin.'],
    ["ROOT-BOOTSTRAP-0026","Bootstrap","Create User Default NOC","POST","/api/v1/user?entity=" + p("entity_l1_a_id"),'{"email":"defnoc@rbac.local","name":"def-noc","currentPassword":"Password123!","userRole":"noc","owner":"' + p("entity_l1_a_id") + '"}','200','ROOT creates User Default NOC.'],
    ["ROOT-BOOTSTRAP-0027","Bootstrap","Create User Default CSR","POST","/api/v1/user?entity=" + p("entity_l1_a_id"),'{"email":"defcsr@rbac.local","name":"def-csr","currentPassword":"Password123!","userRole":"csr","owner":"' + p("entity_l1_a_id") + '"}','200','ROOT creates User Default CSR.'],
    ["ROOT-BOOTSTRAP-0028","Bootstrap","Create User Default Installer","POST","/api/v1/user?entity=" + p("entity_l1_a_id"),'{"email":"definstaller@rbac.local","name":"def-installer","currentPassword":"Password123!","userRole":"installer","owner":"' + p("entity_l1_a_id") + '"}','200','ROOT creates User Default Installer.'],
    ["ROOT-BOOTSTRAP-0029","Bootstrap","Assign System Default Policy Admin to DefAdmin","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-def-admin","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_def_admin_id") + '","users":["' + p("user_def_admin_id") + '"]}','200','ROOT assigns Default System Policy Admin to DefAdmin.'],
    ["ROOT-BOOTSTRAP-0030","Bootstrap","Assign System Default Policy NOC to DefNOC","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-def-noc","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_def_noc_id") + '","users":["' + p("user_def_noc_id") + '"]}','200','ROOT assigns Default System Policy NOC to DefNOC.'],
    ["ROOT-BOOTSTRAP-0031","Bootstrap","Assign System Default Policy CSR to DefCSR","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-def-csr","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_def_csr_id") + '","users":["' + p("user_def_csr_id") + '"]}','200','ROOT assigns Default System Policy CSR to DefCSR.'],
    ["ROOT-BOOTSTRAP-0032","Bootstrap","Assign System Default Policy Installer to DefInstaller","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-def-installer","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_def_installer_id") + '","users":["' + p("user_def_installer_id") + '"]}','200','ROOT assigns Default System Policy Installer to DefInstaller.'],
    ["ROOT-BOOTSTRAP-0033","Bootstrap","Login Default Admin","POST","/api/v1/oauth2",'{"userId":"defadmin@rbac.local","password":"Password123!"}','200','Login Default Admin to capture token_def_admin.'],
    ["ROOT-BOOTSTRAP-0034","Bootstrap","Login Default NOC","POST","/api/v1/oauth2",'{"userId":"defnoc@rbac.local","password":"Password123!"}','200','Login Default NOC to capture token_def_noc.'],
    ["ROOT-BOOTSTRAP-0035","Bootstrap","Login Default CSR","POST","/api/v1/oauth2",'{"userId":"defcsr@rbac.local","password":"Password123!"}','200','Login Default CSR to capture token_def_csr.'],
    ["ROOT-BOOTSTRAP-0036","Bootstrap","Login Default Installer","POST","/api/v1/oauth2",'{"userId":"definstaller@rbac.local","password":"Password123!"}','200','Login Default Installer to capture token_def_installer.'],

    # --- ROOT READ / UPDATE / DELEGATION / AUTOROLE / CONSTRAINTS ---
    ["ROOT-READ-0001","Read","List all entities","GET","/api/v1/entity","","200","ROOT lists all entity objects."],
    ["ROOT-READ-0002","Read","Get Entity A by ID","GET","/api/v1/entity/" + p("entity_l1_a_id"),"","200","ROOT gets Operator A Entity details."],
    ["ROOT-READ-0003","Read","List all operators","GET","/api/v1/operator","","200","ROOT lists all operator objects."],
    ["ROOT-READ-0004","Read","Get Operator A by ID","GET","/api/v1/operator/" + p("operator_a_id"),"","200","ROOT gets Operator A details."],
    ["ROOT-READ-0005","Read","List all venues","GET","/api/v1/venue","","200","ROOT lists all venue objects."],
    ["ROOT-READ-0006","Read","Get Venue 1 details","GET","/api/v1/venue/" + p("venue_l1_1_id"),"","200","ROOT gets Venue 1 details."],
    ["ROOT-READ-0007","Read","List all configurations","GET","/api/v1/configuration","","200","ROOT lists all configuration objects."],
    ["ROOT-READ-0008","Read","Get Configuration A","GET","/api/v1/configuration/" + p("config_a_id"),"","200","ROOT gets Configuration A details."],
    ["ROOT-READ-0009","Read","List all inventory tags","GET","/api/v1/inventory","","200","ROOT lists all inventory tags."],
    ["ROOT-READ-0010","Read","Get Inventory Tag A","GET","/api/v1/inventory/dc6279652f20","","200","ROOT gets Inventory Tag A details."],
    ["ROOT-READ-0011","Read","List all policies","GET","/api/v1/managementPolicy","","200","ROOT lists all management policy objects."],
    ["ROOT-READ-0012","Read","Get Policy A","GET","/api/v1/managementPolicy/" + p("policy_a_id"),"","200","ROOT gets Policy A details."],
    ["ROOT-READ-0013","Read","List all management roles","GET","/api/v1/managementRole","","200","ROOT lists all management role objects."],
    ["ROOT-READ-0014","Read","Get Role A","GET","/api/v1/managementRole/" + p("role_a_id"),"","200","ROOT gets Role A details."],
    ["ROOT-READ-0015","Read","List all subscribers","GET","/api/v1/subuser","","200|400","ROOT lists subscriber users."],
    ["ROOT-READ-0016","Read","Get Subscriber A","GET","/api/v1/subuser/" + p("sub_a_user_id"),"","200","ROOT gets Subscriber A details."],
    ["ROOT-READ-0017","Read","Admin A lists venues in scope","GET","/api/v1/venue","","200","Admin A lists venues within assigned scope."],
    ["ROOT-READ-0018","Read","Admin B lists venues in scope","GET","/api/v1/venue","","200","Admin B lists venues within assigned scope."],

    ["ROOT-UPDATE-0001","Update","Update Operator A description","PUT","/api/v1/operator/" + p("operator_a_id"),'{"description":"Updated Operator A"}',"200","ROOT updates Operator A description."],
    ["ROOT-UPDATE-0002","Update","Update Entity A description","PUT","/api/v1/entity/" + p("entity_l1_a_id"),'{"description":"Updated Entity A"}',"200","ROOT updates Operator A Entity description."],
    ["ROOT-UPDATE-0003","Update","Update Venue 1 description","PUT","/api/v1/venue/" + p("venue_l1_1_id"),'{"description":"Updated Venue 1"}',"200","ROOT updates Venue 1 description."],
    ["ROOT-UPDATE-0004","Update","Update Inventory Tag A description","PUT","/api/v1/inventory/dc6279652f20",'{"description":"Updated Tag A","devClass":"venue"}',"200","ROOT updates Inventory Tag A."],
    ["ROOT-UPDATE-0005","Update","Update Configuration A description","PUT","/api/v1/configuration/" + p("config_a_id"),'{"description":"Updated Config A"}',"200","ROOT updates Configuration A."],
    ["ROOT-UPDATE-0006","Update","Update Policy C description","PUT","/api/v1/managementPolicy/" + p("policy_c_id"),'{"description":"Updated Policy C"}',"200","ROOT updates Policy C."],
    ["ROOT-UPDATE-0007","Update","Update Role A description","PUT","/api/v1/managementRole/" + p("role_a_id"),'{"description":"Updated Role A"}',"200","ROOT updates Role A."],
    ["ROOT-UPDATE-0008","Update","Update Subscriber A description","PUT","/api/v1/subuser/" + p("sub_a_user_id"),'{"description":"Updated Sub A"}',"200","ROOT updates Subscriber A."],

    ["ROOT-DELEGATION-0001","Delegation","Admin A creates Policy Delegated A","POST","/api/v1/managementPolicy/0000-0000-0000",'{"name":"policy-delegated-a","entity":"' + p("entity_l1_a_id") + '","entries":[{"resources":["venue"],"access":["READ"],"effect":"allow"}]}','200|401|403','Admin A creates Policy Delegated A.'],
    ["ROOT-DELEGATION-0002","Delegation","Admin A creates Role Delegated A","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-delegated-a","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_delegated_a_id") + '","users":["' + p("user_delegated_a_id") + '"]}','200|400|401|403','Admin A creates Role Delegated A.'],

    ["ROOT-AUTOROLE-0001","Auto-Role","Admin A creates top-level venue-l1-auto","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-l1-auto","entity":"' + p("entity_l1_a_id") + '"}','200|401|403','Admin A creates venue-l1-auto triggers auto-role.'],
    ["ROOT-AUTOROLE-0002","Auto-Role","Verify auto-created managementRole","GET","/api/v1/managementRole","","200","ROOT verifies auto-created role."],
    ["ROOT-AUTOROLE-0003","Auto-Role","Clean delete auto-role","DELETE","/api/v1/managementRole/" + p("role_auto_id"),"","200|400|401|403|404","Clean delete auto-role."],

    ["ROOT-CONSTRAINT-0001","Constraint","Reject Entity with invalid parent UUID","POST","/api/v1/entity/0",'{"name":"entity-bad-parent","parent":"00000000-0000-0000-0000-999999999999"}','400','Reject Entity with invalid parent.'],
    ["ROOT-CONSTRAINT-0002","Constraint","Reject Entity with circular parent reference","PUT","/api/v1/entity/" + p("entity_l1_a_id"),'{"parent":"' + p("entity_l2_1_id") + '"}','200|400','Reject circular Entity parent reference.'],
    ["ROOT-CONSTRAINT-0003","Constraint","Reject Venue with non-existent parent","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-bad-parent","parent":"00000000-0000-0000-0000-999999999999"}','400','Reject Venue with non-existent parent.'],
    ["ROOT-CONSTRAINT-0004","Constraint","Reject Venue specifying both entity and parent","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-both","entity":"' + p("entity_l1_a_id") + '","parent":"' + p("venue_l1_1_id") + '"}','400','Reject Venue specifying both entity and parent.'],
    ["ROOT-CONSTRAINT-0005","Constraint","Reject Inventory Tag with invalid serialNumber","POST","/api/v1/inventory/invalid_mac",'{"serialNumber":"invalid_mac","name":"tag-bad"}','400','Reject Inventory Tag with invalid serialNumber.'],
    ["ROOT-CONSTRAINT-0006","Constraint","Reject Inventory Tag with non-existent venue","POST","/api/v1/inventory/112233445577",'{"serialNumber":"112233445577","name":"tag-bad-venue","venue":"00000000-0000-0000-0000-999999999999"}','400','Reject Inventory Tag with non-existent venue.'],
    ["ROOT-CONSTRAINT-0007","Constraint","Reject Configuration with invalid JSON body","POST","/api/v1/configuration/0000-0000-0000",'{"name":"config-bad","configuration":[{"name":"globals","configuration":"{invalid-json"}]}','400','Reject Configuration with invalid JSON.'],
    ["ROOT-CONSTRAINT-0008","Constraint","Reject Policy with invalid resource name","POST","/api/v1/managementPolicy/0000-0000-0000",'{"name":"policy-bad-res","entity":"' + p("entity_l1_a_id") + '","entries":[{"resources":["invalid_resource_type"],"access":["READ"],"effect":"allow"}]}','200|400','Reject Policy with invalid resource.'],
    ["ROOT-CONSTRAINT-0009","Constraint","Reject Policy with empty name","POST","/api/v1/managementPolicy/0000-0000-0000",'{"name":"","entity":"' + p("entity_l1_a_id") + '"}','400','Reject Policy creation with empty name.'],
    ["ROOT-CONSTRAINT-0010","Constraint","Reject Role with empty name","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"' + p("policy_a_id") + '"}','400','Reject Role creation with empty name.'],
    ["ROOT-CONSTRAINT-0011","Constraint","Reject Role referencing non-existent policy","POST","/api/v1/managementRole/0000-0000-0000",'{"name":"role-bad-pol","entity":"' + p("entity_l1_a_id") + '","managementPolicy":"00000000-0000-0000-0000-999999999999"}','400','Reject Role creation referencing non-existent policy.'],
    ["ROOT-CONSTRAINT-0012","Constraint","Reject User creation with duplicate email","POST","/api/v1/user",'{"email":"admina@rbac.local","name":"admin-a-dup","currentPassword":"Password123!","userRole":"admin"}','400','Reject User creation with duplicate email.'],
    ["ROOT-CONSTRAINT-0013","Constraint","Reject User creation with weak password","POST","/api/v1/user",'{"email":"weakpass@rbac.local","name":"weak-user","currentPassword":"123","userRole":"admin"}','400','Reject User creation with weak password.'],
    ["ROOT-CONSTRAINT-0014","Constraint","Reject Policy delete when referenced by Role","DELETE","/api/v1/managementPolicy/" + p("policy_a_id"),"","200|400|404","Reject Policy delete when referenced by Role."],
    ["ROOT-CONSTRAINT-0015","Constraint","Reject Operator delete when child Entity exists","DELETE","/api/v1/operator/" + p("operator_a_id"),"","400","Reject Operator delete when child Entity exists."],

    ["ROOT-VENUE-PARENT-0001","Venue Parent","Admin A creates child venue under Venue 1","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-l2-child","parent":"' + p("venue_l1_1_id") + '"}','200|401|403','Admin A creates child venue under Venue 1.'],
    ["ROOT-VENUE-PARENT-0002","Venue Parent","Admin A deletes child venue","DELETE","/api/v1/venue/" + p("venue_l2_1_id"),"","200|401|403|404","Admin A deletes child venue."],

    ["ROOT-VENUE-NONPARENT-0001","Venue Non-Parent","Admin B attempts to create child venue under Venue 1","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-l2-unauth","parent":"' + p("venue_l1_1_id") + '"}','401|403','Admin B attempts to create child venue under Venue 1.'],
    ["ROOT-VENUE-NONPARENT-0002","Venue Non-Parent","Admin B attempts to update Venue 1","PUT","/api/v1/venue/" + p("venue_l1_1_id"),'{"description":"hacked-by-admin-b"}','401|403','Admin B attempts to update Venue 1.'],

    ["ROOT-SHADOW-0001","Shadow Role","Admin A attempts update Venue 1 under shadow role constraints","PUT","/api/v1/venue/" + p("venue_l1_1_id"),'{"description":"authoritative-denial"}','200|401|403','Admin A attempts update Venue 1 under shadow role constraints.'],
    ["ROOT-SHADOW-0002","Shadow Role","Admin A reads Venue 1 under shadow role constraints","GET","/api/v1/venue/" + p("venue_l1_1_id"),"","200","Admin A reads Venue 1 under shadow role constraints."],

    # --- DEFAULT SYSTEM POLICY PERMISSION VERIFICATION TESTS ---
    ["DEF-ADMIN-0001","Default Admin","Default Admin GET Entity A","GET","/api/v1/entity/" + p("entity_l1_a_id"),"","200","Default Admin reads Entity A."],
    ["DEF-ADMIN-0002","Default Admin","Default Admin create Child Venue 3","POST","/api/v1/venue/0000-0000-0000",'{"name":"venue-def-admin","parent":"' + p("venue_l1_1_id") + '"}','200|401|403','Default Admin creates Child Venue 3.'],
    ["DEF-ADMIN-0003","Default Admin","Default Admin update Venue 1 description","PUT","/api/v1/venue/" + p("venue_l1_1_id"),'{"description":"updated-by-def-admin"}','200|401|403','Default Admin updates Venue 1.'],
    ["DEF-ADMIN-0004","Default Admin","Default Admin GET Root Entity","GET","/api/v1/entity/0000-0000-0000","","200|401|403","Default Admin GET Root Entity."],

    ["DEF-NOC-0001","Default NOC","Default NOC GET Entity A","GET","/api/v1/entity/" + p("entity_l1_a_id"),"","200|401|403","Default NOC reads Entity A."],
    ["DEF-NOC-0002","Default NOC","Default NOC GET Venue 1 details","GET","/api/v1/venue/" + p("venue_l1_1_id"),"","200","Default NOC reads Venue 1."],
    ["DEF-NOC-0003","Default NOC","Default NOC update Inventory notes","PUT","/api/v1/inventory/dc6279652f20",'{"description":"def-noc-inv-updated","devClass":"venue"}','200','Default NOC updates Inventory.'],
    ["DEF-NOC-0004","Default NOC","Default NOC attempts to create Normal Entity","POST","/api/v1/entity/0",'{"name":"entity-defnoc-err","parent":"' + p("entity_l1_a_id") + '"}','401|403','Default NOC creates Entity.'],
    ["DEF-NOC-0005","Default NOC","Default NOC attempts to delete Venue 1","DELETE","/api/v1/venue/" + p("venue_l1_1_id"),"","401|403","Default NOC deletes Venue 1."],

    ["DEF-CSR-0001","Default CSR","Default CSR GET Entity A","GET","/api/v1/entity/" + p("entity_l1_a_id"),"","200|401|403","Default CSR reads Entity A."],
    ["DEF-CSR-0002","Default CSR","Default CSR GET Venue 1 details","GET","/api/v1/venue/" + p("venue_l1_1_id"),"","200","Default CSR reads Venue 1."],
    ["DEF-CSR-0003","Default CSR","Default CSR attempts to create Venue","POST","/api/v1/venue/new",'{"name":"venue-defcsr-err","entity":"' + p("entity_l1_a_id") + '"}','401|403','Default CSR creates Venue.'],
    ["DEF-CSR-0004","Default CSR","Default CSR attempts to update Venue 1","PUT","/api/v1/venue/" + p("venue_l1_1_id"),'{"description":"defcsr-hacked-venue"}','401|403','Default CSR updates Venue 1.'],
    ["DEF-CSR-0005","Default CSR","Default CSR attempts to delete Venue 1","DELETE","/api/v1/venue/" + p("venue_l1_1_id"),"","401|403","Default CSR deletes Venue 1."],

    ["DEF-INST-0001","Default Installer","Default Installer GET Venue 1 details","GET","/api/v1/venue/" + p("venue_l1_1_id"),"","200","Default Installer reads Venue 1."],
    ["DEF-INST-0002","Default Installer","Default Installer update Inventory notes","PUT","/api/v1/inventory/dc6279652f20",'{"description":"def-inst-inv-updated","devClass":"venue"}','200','Default Installer updates Inventory.'],
    ["DEF-INST-0003","Default Installer","Default Installer attempts to update Venue 1","PUT","/api/v1/venue/" + p("venue_l1_1_id"),'{"description":"definst-hacked-venue"}','401|403','Default Installer attempts update Venue.'],
    ["DEF-INST-0004","Default Installer","Default Installer attempts to create Normal Entity","POST","/api/v1/entity/0",'{"name":"entity-definst-err","parent":"' + p("entity_l1_a_id") + '"}','401|403','Default Installer creates Entity.'],

    # --- LIFECYCLE CLEANUP (by ROOT) ---
    ["ROOT-LIFECYCLE-0001","Lifecycle","Reject Entity delete with child Venue","DELETE","/api/v1/entity/" + p("entity_l1_a_id"),"","400","Reject Entity delete when child Venue exists."],
    ["ROOT-LIFECYCLE-0002","Lifecycle","Reject Policy delete when in-use","DELETE","/api/v1/managementPolicy/" + p("policy_a_id"),"","200|404","Deleting policy profile."],
    ["ROOT-LIFECYCLE-0003","Lifecycle","Reject Venue delete when child Venue exists","DELETE","/api/v1/venue/" + p("venue_l1_1_id"),"","400","Reject Venue delete when child Venue exists."],
    ["ROOT-LIFECYCLE-0004","Lifecycle","Reject Venue delete when device exists","DELETE","/api/v1/venue/" + p("venue_l1_1_id"),"","400","Reject Venue delete when device exists."],
    ["ROOT-LIFECYCLE-0005","Lifecycle","Clean delete Inventory Tag A","DELETE","/api/v1/inventory/dc6279652f20","","200","Deleting Inventory Tag A."],
    ["ROOT-LIFECYCLE-0006","Lifecycle","Clean delete Child Venue 2","DELETE","/api/v1/venue/" + p("venue_l2_1_id"),"","200","Deleting child Venue 2."],
    ["ROOT-LIFECYCLE-0007","Lifecycle","Clean delete Child Venue 3","DELETE","/api/v1/venue/" + p("venue_def_admin_id"),"","200|404","Deleting Child Venue 3."],
    ["ROOT-LIFECYCLE-0008","Lifecycle","Clean delete Venue 1","DELETE","/api/v1/venue/" + p("venue_l1_1_id"),"","200","Deleting Venue 1."],
    ["ROOT-LIFECYCLE-0009","Lifecycle","Clean delete auto venue-l1-auto","DELETE","/api/v1/venue/" + p("venue_l1_auto_id"),"","200|404","Deleting auto venue."],
    ["ROOT-LIFECYCLE-0010","Lifecycle","Clean delete Subscriber A","DELETE","/api/v1/subuser/" + p("sub_a_user_id"),"","200","Deleting Subscriber A."],
    ["ROOT-LIFECYCLE-0011","Lifecycle","Clean delete Configuration A","DELETE","/api/v1/configuration/" + p("config_a_id"),"","200","Deleting Configuration A."],
    ["ROOT-LIFECYCLE-0012","Lifecycle","Clean delete Role Delegated A","DELETE","/api/v1/managementRole/" + p("role_delegated_a_id"),"","200|404","Deleting Role Delegated A."],
    ["ROOT-LIFECYCLE-0013","Lifecycle","Clean delete Role A","DELETE","/api/v1/managementRole/" + p("role_a_id"),"","200","Deleting Role A."],
    ["ROOT-LIFECYCLE-0014","Lifecycle","Clean delete Policy A second attempt","DELETE","/api/v1/managementPolicy/" + p("policy_a_id"),"","404","Second delete Policy A returns 404."],
    ["ROOT-LIFECYCLE-0015","Lifecycle","ROOT deletes User Client A","DELETE","/api/v1/user/" + p("user_client_a_id"),"","200","ROOT deletes User Client A."],
    ["ROOT-LIFECYCLE-0016","Lifecycle","Verify Client A roles are automatically removed","GET","/api/v1/managementRole/" + p("role_client_a_id"),"","200","Verify Role Client A."],
    ["ROOT-LIFECYCLE-0017","Lifecycle","Clean delete Role Client A","DELETE","/api/v1/managementRole/" + p("role_client_a_id"),"","200","Deleting Role Client A."],
    ["ROOT-LIFECYCLE-0018","Lifecycle","Clean delete User Admin A","DELETE","/api/v1/user/" + p("user_admin_a_id"),"","200","Deleting User Admin A."],
    ["ROOT-LIFECYCLE-0019","Lifecycle","Clean delete User Admin B","DELETE","/api/v1/user/" + p("user_admin_b_id"),"","200","Deleting User Admin B."],
    ["ROOT-LIFECYCLE-0020","Lifecycle","Clean delete User Delegated A","DELETE","/api/v1/user/" + p("user_delegated_a_id"),"","200","Deleting User Delegated A."],
    ["ROOT-LIFECYCLE-0021","Lifecycle","Clean delete User Default Admin","DELETE","/api/v1/user/" + p("user_def_admin_id"),"","200","Deleting User Default Admin."],
    ["ROOT-LIFECYCLE-0022","Lifecycle","Clean delete User Default NOC","DELETE","/api/v1/user/" + p("user_def_noc_id"),"","200","Deleting User Default NOC."],
    ["ROOT-LIFECYCLE-0023","Lifecycle","Clean delete User Default CSR","DELETE","/api/v1/user/" + p("user_def_csr_id"),"","200","Deleting User Default CSR."],
    ["ROOT-LIFECYCLE-0024","Lifecycle","Clean delete User Default Installer","DELETE","/api/v1/user/" + p("user_def_installer_id"),"","200","Deleting User Default Installer."],
    ["ROOT-LIFECYCLE-0025","Lifecycle","Clean delete Role Admin A","DELETE","/api/v1/managementRole/" + p("role_admin_a_id"),"","200","Deleting Role Admin A."],
    ["ROOT-LIFECYCLE-0026","Lifecycle","Clean delete Role Admin B","DELETE","/api/v1/managementRole/" + p("role_admin_b_id"),"","200","Deleting Role Admin B."],
    ["ROOT-LIFECYCLE-0027","Lifecycle","Clean delete Role Venue A","DELETE","/api/v1/managementRole/" + p("role_venue_a_id"),"","200|404","Deleting Role Venue A."],
    ["ROOT-LIFECYCLE-0028","Lifecycle","Clean delete Role Default Admin","DELETE","/api/v1/managementRole/" + p("role_def_admin_id"),"","200","Deleting Role Default Admin."],
    ["ROOT-LIFECYCLE-0029","Lifecycle","Clean delete Role Default NOC","DELETE","/api/v1/managementRole/" + p("role_def_noc_id"),"","200","Deleting Role Default NOC."],
    ["ROOT-LIFECYCLE-0030","Lifecycle","Clean delete Role Default CSR","DELETE","/api/v1/managementRole/" + p("role_def_csr_id"),"","200","Deleting Role Default CSR."],
    ["ROOT-LIFECYCLE-0031","Lifecycle","Clean delete Role Default Installer","DELETE","/api/v1/managementRole/" + p("role_def_installer_id"),"","200","Deleting Role Default Installer."],
    ["ROOT-LIFECYCLE-0032","Lifecycle","Clean delete Policy B","DELETE","/api/v1/managementPolicy/" + p("policy_b_id"),"","200","Deleting Policy B."],
    ["ROOT-LIFECYCLE-0033","Lifecycle","Clean delete Policy C","DELETE","/api/v1/managementPolicy/" + p("policy_c_id"),"","200","Deleting Policy C."],
    ["ROOT-LIFECYCLE-0034","Lifecycle","Clean delete Normal Entity 2","DELETE","/api/v1/entity/" + p("entity_l2_1_id"),"","200","Deleting Normal Entity 2."],
    ["ROOT-LIFECYCLE-0035","Lifecycle","Clean delete Normal Entity 1","DELETE","/api/v1/entity/" + p("entity_l1_1_id"),"","200","Deleting Normal Entity 1."],
    ["ROOT-LIFECYCLE-0036","Lifecycle","Clean delete Operator B","DELETE","/api/v1/operator/" + p("operator_b_id"),"","200","Deleting Operator B."],
    ["ROOT-LIFECYCLE-0037","Lifecycle","Clean delete Operator A","DELETE","/api/v1/operator/" + p("operator_a_id"),"","200","Deleting Operator A."]
]

with open("owprov_rbac_v1_root_lab_test_cases.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(root_rows)

print(f"Generated owprov_rbac_v1_root_lab_test_cases.csv with {len(root_rows)-1} test cases!")

# ==============================================================================
# 2. NON-ROOT ADMIN LAB TEST CASES (owprov_rbac_v1_admin_lab_test_cases.csv)
# ==============================================================================
admin_rows = [
    ['TestCaseID', 'Category', 'Scenario', 'Method', 'Endpoint', 'RequestBody', 'ExpectedStatus', 'Description'],
    ['NONROOT-BOOTSTRAP-0001', 'Bootstrap', 'Verify Root Entity exists', 'GET', '/api/v1/entity/0000-0000-0000', '', '200', 'ROOT retrieves system Root Entity.'],
    ['NONROOT-BOOTSTRAP-0002', 'Bootstrap', 'Create Level 1 Operator A', 'POST', '/api/v1/operator/0000-0000-0000', '{"name":"op-l1-a","registrationId":"operator-a"}', '200', 'ROOT creates Operator A.'],
    ['NONROOT-BOOTSTRAP-0003', 'Bootstrap', 'Create Level 1 Operator B', 'POST', '/api/v1/operator/0000-0000-0000', '{"name":"op-l1-b","registrationId":"operator-b"}', '200', 'ROOT creates Operator B.'],
    ['NONROOT-BOOTSTRAP-0004', 'Bootstrap', 'Create Policy ADMIN-FULL on Entity A', 'POST', '/api/v1/managementPolicy/0000-0000-0000', '{"name":"policy-admin-full","entity":"${entity_l1_a_id}","entries":[{"resources":["entity","venue","managementRole","user","subscriber","inventory","configuration"],"access":["FULL"],"effect":"allow"}]}', '200', 'ROOT creates Policy ADMIN-FULL.'],
    ['NONROOT-BOOTSTRAP-0005', 'Bootstrap', 'Create Policy ADMIN-READ on Entity A', 'POST', '/api/v1/managementPolicy/0000-0000-0000', '{"name":"policy-admin-read","entity":"${entity_l1_a_id}","entries":[{"resources":["entity","venue","inventory","configuration"],"access":["READ"],"effect":"allow"}]}', '200', 'ROOT creates Policy ADMIN-READ.'],
    ['NONROOT-BOOTSTRAP-0006', 'Bootstrap', 'Create Policy NOC on Entity A', 'POST', '/api/v1/managementPolicy/0000-0000-0000', '{"name":"policy-noc","entity":"${entity_l1_a_id}","entries":[{"resources":["entity","venue","inventory","configuration"],"access":["READ"],"effect":"allow"},{"resources":["venue","inventory"],"access":["UPDATE"],"effect":"allow"}]}', '200', 'ROOT creates Policy NOC.'],
    ['NONROOT-BOOTSTRAP-0007', 'Bootstrap', 'Create Policy CSR on Entity A', 'POST', '/api/v1/managementPolicy/0000-0000-0000', '{"name":"policy-csr","entity":"${entity_l1_a_id}","entries":[{"resources":["entity","venue","subscriber","inventory","configuration"],"access":["READ"],"effect":"allow"}]}', '200', 'ROOT creates Policy CSR.'],
    ['NONROOT-BOOTSTRAP-0008', 'Bootstrap', 'Create Policy INSTALLER on Entity A', 'POST', '/api/v1/managementPolicy/0000-0000-0000', '{"name":"policy-installer","entity":"${entity_l1_a_id}","entries":[{"resources":["venue","inventory"],"access":["READ","UPDATE"],"effect":"allow"},{"resources":["configuration"],"access":["READ"],"effect":"allow"}]}', '200', 'ROOT creates Policy INSTALLER.'],
    ['NONROOT-BOOTSTRAP-0009', 'Bootstrap', 'Create Policy ACCOUNTING on Entity A', 'POST', '/api/v1/managementPolicy/0000-0000-0000', '{"name":"policy-accounting","entity":"${entity_l1_a_id}","entries":[{"resources":["subscriber"],"access":["FULL"],"effect":"allow"},{"resources":["entity","venue","inventory","configuration"],"access":["READ"],"effect":"allow"}]}', '200', 'ROOT creates Policy ACCOUNTING.'],
    ['NONROOT-BOOTSTRAP-0010', 'Bootstrap', 'Create User ADMIN FULL', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"adminfull@rbac.local","name":"admin-full","currentPassword":"Password123!","userRole":"admin","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User ADMIN FULL.'],
    ['NONROOT-BOOTSTRAP-0011', 'Bootstrap', 'Create User ADMIN READ', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"adminread@rbac.local","name":"admin-read","currentPassword":"Password123!","userRole":"admin","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User ADMIN READ.'],
    ['NONROOT-BOOTSTRAP-0012', 'Bootstrap', 'Create User NOC', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"nocuser@rbac.local","name":"noc-user","currentPassword":"Password123!","userRole":"noc","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User NOC.'],
    ['NONROOT-BOOTSTRAP-0013', 'Bootstrap', 'Create User CSR', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"csruser@rbac.local","name":"csr-user","currentPassword":"Password123!","userRole":"csr","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User CSR.'],
    ['NONROOT-BOOTSTRAP-0014', 'Bootstrap', 'Create User INSTALLER', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"installeruser@rbac.local","name":"installer-user","currentPassword":"Password123!","userRole":"installer","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User INSTALLER.'],
    ['NONROOT-BOOTSTRAP-0015', 'Bootstrap', 'Create User ACCOUNTING', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"accountinguser@rbac.local","name":"accounting-user","currentPassword":"Password123!","userRole":"accounting","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User ACCOUNTING.'],
    ['NONROOT-BOOTSTRAP-0016', 'Bootstrap', 'Create Top Venue 1 under Entity A', 'POST', '/api/v1/venue/new', '{"name":"venue-l1-main","entity":"${entity_l1_a_id}"}', '200', 'ROOT creates Top Venue 1.'],
    ['NONROOT-BOOTSTRAP-0017', 'Bootstrap', 'Assign Role ADMIN FULL', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-admin-full","entity":"${entity_l1_a_id}","managementPolicy":"${policy_admin_full_id}","users":["${user_admin_full_id}"]}', '200', 'ROOT assigns Role ADMIN FULL.'],
    ['NONROOT-BOOTSTRAP-0018', 'Bootstrap', 'Assign Role ADMIN READ', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-admin-read","entity":"${entity_l1_a_id}","managementPolicy":"${policy_admin_read_id}","users":["${user_admin_read_id}"]}', '200', 'ROOT assigns Role ADMIN READ.'],
    ['NONROOT-BOOTSTRAP-0019', 'Bootstrap', 'Assign Role NOC', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-noc","entity":"${entity_l1_a_id}","managementPolicy":"${policy_noc_id}","users":["${user_noc_id}"]}', '200', 'ROOT assigns Role NOC.'],
    ['NONROOT-BOOTSTRAP-0020', 'Bootstrap', 'Assign Role CSR', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-csr","entity":"${entity_l1_a_id}","managementPolicy":"${policy_csr_id}","users":["${user_csr_id}"]}', '200', 'ROOT assigns Role CSR.'],
    ['NONROOT-BOOTSTRAP-0021', 'Bootstrap', 'Assign Role INSTALLER', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-installer","entity":"${entity_l1_a_id}","managementPolicy":"${policy_installer_id}","users":["${user_installer_id}"]}', '200', 'ROOT assigns Role INSTALLER.'],
    ['NONROOT-BOOTSTRAP-0022', 'Bootstrap', 'Assign Role ACCOUNTING', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-accounting","entity":"${entity_l1_a_id}","managementPolicy":"${policy_accounting_id}","users":["${user_accounting_id}"]}', '200', 'ROOT assigns Role ACCOUNTING.'],
    ['NONROOT-BOOTSTRAP-0023', 'Bootstrap', 'Login Admin Full User', 'POST', '/api/v1/oauth2', '{"userId":"adminfull@rbac.local","password":"Password123!"}', '200', 'Login Admin Full User.'],
    ['NONROOT-BOOTSTRAP-0024', 'Bootstrap', 'Login Admin Read User', 'POST', '/api/v1/oauth2', '{"userId":"adminread@rbac.local","password":"Password123!"}', '200', 'Login Admin Read User.'],
    ['NONROOT-BOOTSTRAP-0025', 'Bootstrap', 'Login NOC User', 'POST', '/api/v1/oauth2', '{"userId":"nocuser@rbac.local","password":"Password123!"}', '200', 'Login NOC User.'],
    ['NONROOT-BOOTSTRAP-0026', 'Bootstrap', 'Login CSR User', 'POST', '/api/v1/oauth2', '{"userId":"csruser@rbac.local","password":"Password123!"}', '200', 'Login CSR User.'],
    ['NONROOT-BOOTSTRAP-0027', 'Bootstrap', 'Login INSTALLER User', 'POST', '/api/v1/oauth2', '{"userId":"installeruser@rbac.local","password":"Password123!"}', '200', 'Login INSTALLER User.'],
    ['NONROOT-BOOTSTRAP-0028', 'Bootstrap', 'Login ACCOUNTING User', 'POST', '/api/v1/oauth2', '{"userId":"accountinguser@rbac.local","password":"Password123!"}', '200', 'Login ACCOUNTING User.'],
    ['NONROOT-BOOTSTRAP-0029', 'Bootstrap', 'Create Inventory Tag by ROOT', 'POST', '/api/v1/inventory/112233445566', '{"serialNumber":"112233445566","name":"inv-1","deviceType":"asus_rt-ax53u","devGroup":"ap","devClass":"venue","venue":"${venue_l1_1_id}"}', '200', 'ROOT creates Inventory Tag.'],
    ['NONROOT-BOOTSTRAP-0030', 'Bootstrap', 'Create Configuration by ROOT', 'POST', '/api/v1/configuration/0', '{"name":"cfg-main","deviceTypes":["asus_rt-ax53u"],"entity":"${entity_l1_a_id}","venue":"${venue_l1_1_id}"}', '200', 'ROOT creates Configuration.'],
    ['DEFAULT-BOOTSTRAP-0001', 'Default Bootstrap', 'Create User Default Admin', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"defadmin@rbac.local","name":"def-admin","currentPassword":"Password123!","userRole":"admin","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User Default Admin.'],
    ['DEFAULT-BOOTSTRAP-0002', 'Default Bootstrap', 'Create User Default NOC', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"defnoc@rbac.local","name":"def-noc","currentPassword":"Password123!","userRole":"noc","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User Default NOC.'],
    ['DEFAULT-BOOTSTRAP-0003', 'Default Bootstrap', 'Create User Default CSR', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"defcsr@rbac.local","name":"def-csr","currentPassword":"Password123!","userRole":"csr","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User Default CSR.'],
    ['DEFAULT-BOOTSTRAP-0004', 'Default Bootstrap', 'Create User Default Installer', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"definstaller@rbac.local","name":"def-installer","currentPassword":"Password123!","userRole":"installer","owner":"${entity_l1_a_id}"}', '200', 'ROOT creates User Default Installer.'],
    ['DEFAULT-BOOTSTRAP-0005', 'Default Bootstrap', 'Assign System Default Policy Admin to DefAdmin', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-def-admin","entity":"${entity_l1_a_id}","managementPolicy":"${policy_def_admin_id}","users":["${user_def_admin_id}"]}', '200', 'ROOT assigns Default Policy Admin.'],
    ['DEFAULT-BOOTSTRAP-0006', 'Default Bootstrap', 'Assign System Default Policy NOC to DefNOC', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-def-noc","entity":"${entity_l1_a_id}","managementPolicy":"${policy_def_noc_id}","users":["${user_def_noc_id}"]}', '200', 'ROOT assigns Default Policy NOC.'],
    ['DEFAULT-BOOTSTRAP-0007', 'Default Bootstrap', 'Assign System Default Policy CSR to DefCSR', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-def-csr","entity":"${entity_l1_a_id}","managementPolicy":"${policy_def_csr_id}","users":["${user_def_csr_id}"]}', '200', 'ROOT assigns Default Policy CSR.'],
    ['DEFAULT-BOOTSTRAP-0008', 'Default Bootstrap', 'Assign System Default Policy Installer to DefInstaller', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-def-installer","entity":"${entity_l1_a_id}","managementPolicy":"${policy_def_installer_id}","users":["${user_def_installer_id}"]}', '200', 'ROOT assigns Default Policy Installer.'],
    ['DEFAULT-BOOTSTRAP-0009', 'Default Bootstrap', 'Login Default Admin', 'POST', '/api/v1/oauth2', '{"userId":"defadmin@rbac.local","password":"Password123!"}', '200', 'Login Default Admin.'],
    ['DEFAULT-BOOTSTRAP-0010', 'Default Bootstrap', 'Login Default NOC', 'POST', '/api/v1/oauth2', '{"userId":"defnoc@rbac.local","password":"Password123!"}', '200', 'Login Default NOC.'],
    ['DEFAULT-BOOTSTRAP-0011', 'Default Bootstrap', 'Login Default CSR', 'POST', '/api/v1/oauth2', '{"userId":"defcsr@rbac.local","password":"Password123!"}', '200', 'Login Default CSR.'],
    ['DEFAULT-BOOTSTRAP-0012', 'Default Bootstrap', 'Login Default Installer', 'POST', '/api/v1/oauth2', '{"userId":"definstaller@rbac.local","password":"Password123!"}', '200', 'Login Default Installer.'],
    ['ADMIN-FULL-0001', 'ADMIN Full User', 'Admin Full GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'Admin Full reads Entity A.'],
    ['ADMIN-FULL-0002', 'ADMIN Full User', 'Admin Full create Level 2 Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-l2-admin","parent":"${entity_l1_a_id}"}', '200', 'Admin Full creates Level 2 Entity.'],
    ['ADMIN-FULL-0003', 'ADMIN Full User', 'Admin Full create Child Venue 2', 'POST', '/api/v1/venue/0', '{"name":"venue-l2-admin","parent":"${venue_l1_1_id}"}', '200', 'Admin Full creates Child Venue 2.'],
    ['ADMIN-FULL-0004', 'ADMIN Full User', 'Admin Full update Venue 1 description', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"updated-by-admin-full"}', '200', 'Admin Full updates Venue 1.'],
    ['ADMIN-FULL-0005', 'ADMIN Full User', 'Admin Full attempt create L3 Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-l3-err","parent":"${entity_l2_admin_id}"}', '400', 'Admin Full attempt create L3 Entity.'],
    ['ADMIN-FULL-0006', 'ADMIN Full User', 'Admin Full GET Root Entity', 'GET', '/api/v1/entity/0000-0000-0000', '', '401|403', 'Admin Full GET Root Entity.'],
    ['ADMIN-FULL-0007', 'ADMIN Full User', 'Admin Full GET sibling Entity B', 'GET', '/api/v1/entity/${entity_l1_b_id}', '', '401|403', 'Admin Full GET Sibling Entity B.'],
    ['ADMIN-FULL-0008', 'ADMIN Full User', 'Admin Full POST Operator', 'POST', '/api/v1/operator/0000-0000-0000', '{"name":"op-unauth","registrationId":"op-unauth"}', '401|403', 'Admin Full POST Operator.'],
    ['ADMIN-FULL-0009', 'ADMIN Full User', 'Admin Full GET Inventory', 'GET', '/api/v1/inventory/112233445566', '', '200', 'Admin Full reads Inventory Tag.'],
    ['ADMIN-FULL-0010', 'ADMIN Full User', 'Admin Full GET Configuration', 'GET', '/api/v1/configuration/${config_a_id}', '', '200', 'Admin Full reads Configuration.'],
    ['ADMIN-FULL-0011', 'ADMIN Full User', 'Admin Full update Inventory description', 'PUT', '/api/v1/inventory/112233445566', '{"description":"updated-by-admin-full","devClass":"venue"}', '200', 'Admin Full updates Inventory.'],
    ['ADMIN-READ-0001', 'ADMIN Read User', 'Admin Read GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'Admin Read GET Entity A.'],
    ['ADMIN-READ-0002', 'ADMIN Read User', 'Admin Read attempt create Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-read-err","parent":"${entity_l1_a_id}"}', '401|403', 'Admin Read attempt create Entity.'],
    ['ADMIN-READ-0003', 'ADMIN Read User', 'Admin Read attempt update Venue 1', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"read-hacked-venue"}', '401|403', 'Admin Read attempt update Venue 1.'],
    ['ADMIN-READ-0004', 'ADMIN Read User', 'Admin Read GET Inventory', 'GET', '/api/v1/inventory/112233445566', '', '200', 'Admin Read reads Inventory.'],
    ['ADMIN-READ-0005', 'ADMIN Read User', 'Admin Read GET Configuration', 'GET', '/api/v1/configuration/${config_a_id}', '', '200', 'Admin Read reads Configuration.'],
    ['ADMIN-READ-0006', 'ADMIN Read User', 'Admin Read attempt update Configuration', 'PUT', '/api/v1/configuration/${config_a_id}', '{"description":"hacked-cfg"}', '401|403', 'Admin Read attempt update Configuration.'],
    ['ADMIN-DELEGATION-0001', 'ADMIN Sub-User Delegation', 'Admin Full creates Sub-User 1', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"subuser1@rbac.local","name":"sub-user-1","currentPassword":"Password123!","userRole":"admin","owner":"${entity_l1_a_id}"}', '200', 'Admin Full creates Sub-User 1.'],
    ['ADMIN-DELEGATION-0002', 'ADMIN Sub-User Delegation', 'Admin Full assigns Role 1 to Sub-User 1', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-sub-l1","entity":"${entity_l1_a_id}","managementPolicy":"${policy_admin_full_id}","users":["${user_sub_l1_id}"]}', '200', 'Admin Full assigns Role 1 to Sub-User 1.'],
    ['ADMIN-DELEGATION-0003', 'ADMIN Sub-User Delegation', 'Login Sub-User 1', 'POST', '/api/v1/oauth2', '{"userId":"subuser1@rbac.local","password":"Password123!"}', '200', 'Login Sub-User 1.'],
    ['ADMIN-SUBVERIFY-0001', 'Sub-User Verification', 'Sub-User 1 reads Venue 1', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'Sub-User 1 reads Venue 1.'],
    ['ADMIN-SUBVERIFY-0002', 'Sub-User Verification', 'Sub-User 1 updates Venue 1', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"updated-by-subuser1"}', '200', 'Sub-User 1 updates Venue 1.'],
    ['NOC-POS-0001', 'NOC User', 'NOC GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'NOC User reads Entity A.'],
    ['NOC-POS-0002', 'NOC User', 'NOC GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'NOC User reads Venue 1 details.'],
    ['NOC-POS-0003', 'NOC User', 'NOC update Venue 1 maintenance note', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"noc-maintenance-updated"}', '200', 'NOC User updates Venue 1.'],
    ['NOC-POS-0004', 'NOC User', 'NOC GET Inventory', 'GET', '/api/v1/inventory/112233445566', '', '200', 'NOC User reads Inventory.'],
    ['NOC-POS-0005', 'NOC User', 'NOC GET Configuration', 'GET', '/api/v1/configuration/${config_a_id}', '', '200', 'NOC User reads Configuration.'],
    ['NOC-POS-0006', 'NOC User', 'NOC update Inventory maintenance note', 'PUT', '/api/v1/inventory/112233445566', '{"description":"noc-inv-updated","devClass":"venue"}', '200', 'NOC User updates Inventory.'],
    ['NOC-NEG-0001', 'NOC User', 'NOC attempts to create Normal Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-noc-err","parent":"${entity_l1_a_id}"}', '401|403', 'NOC User creates Entity.'],
    ['NOC-NEG-0002', 'NOC User', 'NOC attempts to delete Venue 1', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '401|403', 'NOC User deletes Venue 1.'],
    ['NOC-NEG-0003', 'NOC User', 'NOC attempts to create User', 'POST', '/api/v1/user?entity=${entity_l1_a_id}', '{"email":"nocsub@rbac.local","name":"noc-sub","currentPassword":"Password123!","userRole":"csr"}', '401|403', 'NOC User creates User.'],
    ['NOC-NEG-0004', 'NOC User', 'NOC attempts to update Configuration', 'PUT', '/api/v1/configuration/${config_a_id}', '{"description":"noc-hacked-cfg"}', '401|403', 'NOC User updates Configuration.'],
    ['NOC-NEG-0005', 'NOC User', 'NOC attempts to delete Configuration', 'DELETE', '/api/v1/configuration/${config_a_id}', '', '401|403', 'NOC User deletes Configuration.'],
    ['CSR-POS-0001', 'CSR User', 'CSR GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'CSR User reads Entity A.'],
    ['CSR-POS-0002', 'CSR User', 'CSR GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'CSR User reads Venue 1 details.'],
    ['CSR-POS-0003', 'CSR User', 'CSR GET Inventory', 'GET', '/api/v1/inventory/112233445566', '', '200', 'CSR User reads Inventory.'],
    ['CSR-POS-0004', 'CSR User', 'CSR GET Configuration', 'GET', '/api/v1/configuration/${config_a_id}', '', '200', 'CSR User reads Configuration.'],
    ['CSR-NEG-0001', 'CSR User', 'CSR attempts to create Venue', 'POST', '/api/v1/venue/new', '{"name":"venue-csr-err","entity":"${entity_l1_a_id}"}', '401|403', 'CSR User creates Venue.'],
    ['CSR-NEG-0002', 'CSR User', 'CSR attempts to update Venue 1', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"csr-hacked-venue"}', '401|403', 'CSR User updates Venue 1.'],
    ['CSR-NEG-0003', 'CSR User', 'CSR attempts to delete Venue 1', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '401|403', 'CSR User deletes Venue 1.'],
    ['CSR-NEG-0004', 'CSR User', 'CSR attempts to update Inventory', 'PUT', '/api/v1/inventory/112233445566', '{"description":"csr-hacked-inv","devClass":"venue"}', '401|403', 'CSR User updates Inventory.'],
    ['CSR-NEG-0005', 'CSR User', 'CSR attempts to update Configuration', 'PUT', '/api/v1/configuration/${config_a_id}', '{"description":"csr-hacked-cfg"}', '401|403', 'CSR User updates Configuration.'],
    ['INSTALLER-POS-0001', 'INSTALLER User', 'Installer GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'Installer User reads Venue 1.'],
    ['INSTALLER-POS-0002', 'INSTALLER User', 'Installer update Venue 1 onboard notes', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"installer-device-onboarded"}', '200', 'Installer User updates Venue 1.'],
    ['INSTALLER-POS-0003', 'INSTALLER User', 'Installer GET Inventory', 'GET', '/api/v1/inventory/112233445566', '', '200', 'Installer User reads Inventory.'],
    ['INSTALLER-POS-0004', 'INSTALLER User', 'Installer update Inventory onboard notes', 'PUT', '/api/v1/inventory/112233445566', '{"description":"installer-inv-onboarded","devClass":"venue"}', '200', 'Installer User updates Inventory.'],
    ['INSTALLER-POS-0005', 'INSTALLER User', 'Installer GET Configuration', 'GET', '/api/v1/configuration/${config_a_id}', '', '200', 'Installer User reads Configuration.'],
    ['INSTALLER-NEG-0001', 'INSTALLER User', 'Installer attempts to create Normal Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-inst-err","parent":"${entity_l1_a_id}"}', '401|403', 'Installer User creates Entity.'],
    ['INSTALLER-NEG-0002', 'INSTALLER User', 'Installer attempts to delete Venue 1', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '401|403', 'Installer User deletes Venue 1.'],
    ['INSTALLER-NEG-0003', 'INSTALLER User', 'Installer attempts to assign Role', 'POST', '/api/v1/managementRole/0000-0000-0000', '{"name":"role-inst-err","entity":"${entity_l1_a_id}","managementPolicy":"${policy_admin_full_id}","users":["${user_installer_id}"]}', '401|403', 'Installer User assigns Role.'],
    ['INSTALLER-NEG-0004', 'INSTALLER User', 'Installer attempts to update Configuration', 'PUT', '/api/v1/configuration/${config_a_id}', '{"description":"installer-hacked-cfg"}', '401|403', 'Installer User updates Configuration.'],
    ['ACCOUNTING-POS-0001', 'ACCOUNTING User', 'Accounting GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'Accounting User reads Entity A.'],
    ['ACCOUNTING-POS-0002', 'ACCOUNTING User', 'Accounting GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'Accounting User reads Venue 1.'],
    ['ACCOUNTING-POS-0003', 'ACCOUNTING User', 'Accounting GET Inventory', 'GET', '/api/v1/inventory/112233445566', '', '200', 'Accounting User reads Inventory.'],
    ['ACCOUNTING-POS-0004', 'ACCOUNTING User', 'Accounting GET Configuration', 'GET', '/api/v1/configuration/${config_a_id}', '', '200', 'Accounting User reads Configuration.'],
    ['ACCOUNTING-NEG-0001', 'ACCOUNTING User', 'Accounting attempts to update Venue 1', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"acct-hacked-venue"}', '401|403', 'Accounting User updates Venue 1.'],
    ['ACCOUNTING-NEG-0002', 'ACCOUNTING User', 'Accounting attempts to create Venue', 'POST', '/api/v1/venue/new', '{"name":"venue-acct-err","entity":"${entity_l1_a_id}"}', '401|403', 'Accounting User creates Venue.'],
    ['ACCOUNTING-NEG-0003', 'ACCOUNTING User', 'Accounting attempts to delete Venue 1', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '401|403', 'Accounting User deletes Venue 1.'],
    ['ACCOUNTING-NEG-0004', 'ACCOUNTING User', 'Accounting attempts to update Inventory', 'PUT', '/api/v1/inventory/112233445566', '{"description":"acct-hacked-inv","devClass":"venue"}', '401|403', 'Accounting User updates Inventory.'],
    ['ACCOUNTING-NEG-0005', 'ACCOUNTING User', 'Accounting attempts to update Configuration', 'PUT', '/api/v1/configuration/${config_a_id}', '{"description":"acct-hacked-cfg"}', '401|403', 'Accounting User updates Configuration.'],
    ['DEF-ADMIN-0001', 'Default Admin', 'Default Admin GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'Default Admin reads Entity A.'],
    ['DEF-ADMIN-0002', 'Default Admin', 'Default Admin create Child Venue 3', 'POST', '/api/v1/venue/0', '{"name":"venue-def-admin","parent":"${venue_l1_1_id}"}', '200', 'Default Admin creates Child Venue 3.'],
    ['DEF-ADMIN-0003', 'Default Admin', 'Default Admin update Venue 1 description', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"updated-by-def-admin"}', '200', 'Default Admin updates Venue 1.'],
    ['DEF-ADMIN-0004', 'Default Admin', 'Default Admin GET Root Entity', 'GET', '/api/v1/entity/0000-0000-0000', '', '401|403', 'Default Admin GET Root Entity.'],
    ['DEF-NOC-0001', 'Default NOC', 'Default NOC GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'Default NOC reads Entity A.'],
    ['DEF-NOC-0002', 'Default NOC', 'Default NOC GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'Default NOC reads Venue 1.'],
    ['DEF-NOC-0003', 'Default NOC', 'Default NOC update Inventory notes', 'PUT', '/api/v1/inventory/112233445566', '{"description":"def-noc-inv-updated","devClass":"venue"}', '200', 'Default NOC updates Inventory.'],
    ['DEF-NOC-0004', 'Default NOC', 'Default NOC attempts to create Normal Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-defnoc-err","parent":"${entity_l1_a_id}"}', '401|403', 'Default NOC creates Entity.'],
    ['DEF-NOC-0005', 'Default NOC', 'Default NOC attempts to delete Venue 1', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '401|403', 'Default NOC deletes Venue 1.'],
    ['DEF-CSR-0001', 'Default CSR', 'Default CSR GET Entity A', 'GET', '/api/v1/entity/${entity_l1_a_id}', '', '200', 'Default CSR reads Entity A.'],
    ['DEF-CSR-0002', 'Default CSR', 'Default CSR GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'Default CSR reads Venue 1.'],
    ['DEF-CSR-0003', 'Default CSR', 'Default CSR attempts to create Venue', 'POST', '/api/v1/venue/new', '{"name":"venue-defcsr-err","entity":"${entity_l1_a_id}"}', '401|403', 'Default CSR creates Venue.'],
    ['DEF-CSR-0004', 'Default CSR', 'Default CSR attempts to update Venue 1', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"defcsr-hacked-venue"}', '401|403', 'Default CSR updates Venue 1.'],
    ['DEF-CSR-0005', 'Default CSR', 'Default CSR attempts to delete Venue 1', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '401|403', 'Default CSR deletes Venue 1.'],
    ['DEF-INST-0001', 'Default Installer', 'Default Installer GET Venue 1 details', 'GET', '/api/v1/venue/${venue_l1_1_id}', '', '200', 'Default Installer reads Venue 1.'],
    ['DEF-INST-0002', 'Default Installer', 'Default Installer update Inventory notes', 'PUT', '/api/v1/inventory/112233445566', '{"description":"def-inst-inv-updated","devClass":"venue"}', '200', 'Default Installer updates Inventory.'],
    ['DEF-INST-0003', 'Default Installer', 'Default Installer attempts to update Venue 1', 'PUT', '/api/v1/venue/${venue_l1_1_id}', '{"description":"definst-hacked-venue"}', '401|403', 'Default Installer attempts update Venue.'],
    ['DEF-INST-0004', 'Default Installer', 'Default Installer attempts to create Normal Entity', 'POST', '/api/v1/entity/0', '{"name":"entity-definst-err","parent":"${entity_l1_a_id}"}', '401|403', 'Default Installer creates Entity.'],
    ['NONROOT-LIFECYCLE-0001', 'Lifecycle', 'Delete Inventory Tag by ROOT', 'DELETE', '/api/v1/inventory/112233445566', '', '200|404', 'ROOT deletes Inventory Tag.'],
    ['NONROOT-LIFECYCLE-0002', 'Lifecycle', 'Delete Configuration by ROOT', 'DELETE', '/api/v1/configuration/${config_a_id}', '', '200|404', 'ROOT deletes Configuration.'],
    ['NONROOT-LIFECYCLE-0003', 'Lifecycle', 'Delete Sub-User 1 by ROOT', 'DELETE', '/api/v1/user/${user_sub_l1_id}', '', '200|404', 'ROOT deletes Sub-User 1.'],
    ['NONROOT-LIFECYCLE-0004', 'Lifecycle', 'Delete Child Venue 2 by ROOT', 'DELETE', '/api/v1/venue/${venue_l2_admin_id}', '', '200|404', 'ROOT deletes Child Venue 2.'],
    ['NONROOT-LIFECYCLE-0005', 'Lifecycle', 'Delete Child Venue 3 by ROOT', 'DELETE', '/api/v1/venue/${venue_def_admin_id}', '', '200|404', 'ROOT deletes Child Venue 3.'],
    ['NONROOT-LIFECYCLE-0006', 'Lifecycle', 'Delete Level 2 Entity by ROOT', 'DELETE', '/api/v1/entity/${entity_l2_admin_id}', '', '200|404', 'ROOT deletes Level 2 Entity.'],
    ['NONROOT-LIFECYCLE-0007', 'Lifecycle', 'Delete Top Venue 1 by ROOT', 'DELETE', '/api/v1/venue/${venue_l1_1_id}', '', '200|404', 'ROOT deletes Top Venue 1.'],
    ['NONROOT-LIFECYCLE-0008', 'Lifecycle', 'Delete User Sub-User 1 Role by ROOT', 'DELETE', '/api/v1/managementRole/${role_sub_l1_id}', '', '200|404', 'ROOT deletes Sub-User Role.'],
    ['NONROOT-LIFECYCLE-0009', 'Lifecycle', 'Delete User Default Admin by ROOT', 'DELETE', '/api/v1/user/${user_def_admin_id}', '', '200|404', 'ROOT deletes Default Admin.'],
    ['NONROOT-LIFECYCLE-0010', 'Lifecycle', 'Delete User Default NOC by ROOT', 'DELETE', '/api/v1/user/${user_def_noc_id}', '', '200|404', 'ROOT deletes Default NOC.'],
    ['NONROOT-LIFECYCLE-0011', 'Lifecycle', 'Delete User Default CSR by ROOT', 'DELETE', '/api/v1/user/${user_def_csr_id}', '', '200|404', 'ROOT deletes Default CSR.'],
    ['NONROOT-LIFECYCLE-0012', 'Lifecycle', 'Delete User Default Installer by ROOT', 'DELETE', '/api/v1/user/${user_def_installer_id}', '', '200|404', 'ROOT deletes Default Installer.'],
    ['NONROOT-LIFECYCLE-0013', 'Lifecycle', 'Delete User Admin Full by ROOT', 'DELETE', '/api/v1/user/${user_admin_full_id}', '', '200|404', 'ROOT deletes User Admin Full.'],
    ['NONROOT-LIFECYCLE-0014', 'Lifecycle', 'Delete User Admin Read by ROOT', 'DELETE', '/api/v1/user/${user_admin_read_id}', '', '200|404', 'ROOT deletes User Admin Read.'],
    ['NONROOT-LIFECYCLE-0015', 'Lifecycle', 'Delete User NOC by ROOT', 'DELETE', '/api/v1/user/${user_noc_id}', '', '200|404', 'ROOT deletes User NOC.'],
    ['NONROOT-LIFECYCLE-0016', 'Lifecycle', 'Delete User CSR by ROOT', 'DELETE', '/api/v1/user/${user_csr_id}', '', '200|404', 'ROOT deletes User CSR.'],
    ['NONROOT-LIFECYCLE-0017', 'Lifecycle', 'Delete User Installer by ROOT', 'DELETE', '/api/v1/user/${user_installer_id}', '', '200|404', 'ROOT deletes User Installer.'],
    ['NONROOT-LIFECYCLE-0018', 'Lifecycle', 'Delete User Accounting by ROOT', 'DELETE', '/api/v1/user/${user_accounting_id}', '', '200|404', 'ROOT deletes User Accounting.'],
    ['NONROOT-LIFECYCLE-0019', 'Lifecycle', 'Delete Role Default Admin by ROOT', 'DELETE', '/api/v1/managementRole/${role_def_admin_id}', '', '200|404', 'ROOT deletes Default Admin Role.'],
    ['NONROOT-LIFECYCLE-0020', 'Lifecycle', 'Delete Role Default NOC by ROOT', 'DELETE', '/api/v1/managementRole/${role_def_noc_id}', '', '200|404', 'ROOT deletes Default NOC Role.'],
    ['NONROOT-LIFECYCLE-0021', 'Lifecycle', 'Delete Role Default CSR by ROOT', 'DELETE', '/api/v1/managementRole/${role_def_csr_id}', '', '200|404', 'ROOT deletes Default CSR Role.'],
    ['NONROOT-LIFECYCLE-0022', 'Lifecycle', 'Delete Role Default Installer by ROOT', 'DELETE', '/api/v1/managementRole/${role_def_installer_id}', '', '200|404', 'ROOT deletes Default Installer Role.'],
    ['NONROOT-LIFECYCLE-0023', 'Lifecycle', 'Delete Role Admin Full by ROOT', 'DELETE', '/api/v1/managementRole/${role_admin_full_id}', '', '200|404', 'ROOT deletes Role Admin Full.'],
    ['NONROOT-LIFECYCLE-0024', 'Lifecycle', 'Delete Role Admin Read by ROOT', 'DELETE', '/api/v1/managementRole/${role_admin_read_id}', '', '200|404', 'ROOT deletes Role Admin Read.'],
    ['NONROOT-LIFECYCLE-0025', 'Lifecycle', 'Delete Role NOC by ROOT', 'DELETE', '/api/v1/managementRole/${role_noc_id}', '', '200|404', 'ROOT deletes Role NOC.'],
    ['NONROOT-LIFECYCLE-0026', 'Lifecycle', 'Delete Role CSR by ROOT', 'DELETE', '/api/v1/managementRole/${role_csr_id}', '', '200|404', 'ROOT deletes Role CSR.'],
    ['NONROOT-LIFECYCLE-0027', 'Lifecycle', 'Delete Role Installer by ROOT', 'DELETE', '/api/v1/managementRole/${role_installer_id}', '', '200|404', 'ROOT deletes Role Installer.'],
    ['NONROOT-LIFECYCLE-0028', 'Lifecycle', 'Delete Role Accounting by ROOT', 'DELETE', '/api/v1/managementRole/${role_accounting_id}', '', '200|404', 'ROOT deletes Role Accounting.'],
    ['NONROOT-LIFECYCLE-0029', 'Lifecycle', 'Delete Policy ADMIN-FULL by ROOT', 'DELETE', '/api/v1/managementPolicy/${policy_admin_full_id}', '', '200|404', 'ROOT deletes Policy ADMIN-FULL.'],
    ['NONROOT-LIFECYCLE-0030', 'Lifecycle', 'Delete Policy ADMIN-READ by ROOT', 'DELETE', '/api/v1/managementPolicy/${policy_admin_read_id}', '', '200|404', 'ROOT deletes Policy ADMIN-READ.'],
    ['NONROOT-LIFECYCLE-0031', 'Lifecycle', 'Delete Policy NOC by ROOT', 'DELETE', '/api/v1/managementPolicy/${policy_noc_id}', '', '200|404', 'ROOT deletes Policy NOC.'],
    ['NONROOT-LIFECYCLE-0032', 'Lifecycle', 'Delete Policy CSR by ROOT', 'DELETE', '/api/v1/managementPolicy/${policy_csr_id}', '', '200|404', 'ROOT deletes Policy CSR.'],
    ['NONROOT-LIFECYCLE-0033', 'Lifecycle', 'Delete Policy INSTALLER by ROOT', 'DELETE', '/api/v1/managementPolicy/${policy_installer_id}', '', '200|404', 'ROOT deletes Policy INSTALLER.'],
    ['NONROOT-LIFECYCLE-0034', 'Lifecycle', 'Delete Policy ACCOUNTING by ROOT', 'DELETE', '/api/v1/managementPolicy/${policy_accounting_id}', '', '200|404', 'ROOT deletes Policy ACCOUNTING.'],
    ['NONROOT-LIFECYCLE-0035', 'Lifecycle', 'Delete Operator B by ROOT', 'DELETE', '/api/v1/operator/${operator_b_id}', '', '200|404', 'ROOT deletes Operator B.'],
    ['NONROOT-LIFECYCLE-0036', 'Lifecycle', 'Delete Operator A by ROOT', 'DELETE', '/api/v1/operator/${operator_a_id}', '', '200|404', 'ROOT deletes Operator A.']
]

with open("owprov_rbac_v1_admin_lab_test_cases.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(admin_rows)

print(f"Generated owprov_rbac_v1_admin_lab_test_cases.csv with {len(admin_rows)-1} test cases!")
